
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lifeos-network

  backend:
    build: ./server
    container_name: lifeos-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/lifeos
      - JWT_SECRET=69babb8195bc2dfeec9f98b6
      - EMAIL_USER=sameerahmadsaifi@gmail.com
      - EMAIL_PASS=qtqn qcxl mjoo bycn
      - CLIENT_URL=http://localhost
    depends_on:
      - mongodb
    networks:
      - lifeos-network

  frontend:
    build: ./client
    container_name: lifeos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - lifeos-network

networks:
  lifeos-network:
    driver: bridge

volumes:
  mongo-data:
